### ISSUE TITLE
Duplicação de código

### ISSUE THREAD

**Issue by mstrcnvs** [ttnunes/manga-list#1]
https://github.com/ttnunes/manga-list/blob/f80f5b16a7c323a343e9f84deee0c975dc1ee6c2/src/components/CharactersList/index.tsx#L75

Boa noite Thiago, tudo bem?

Percebi que essa função `loadCharacters` está sendo definida duas vezes, sendo que quase não há diferença entre as duas. Também percebi que ela serve basicamente para buscar os dados da API e traduzir para entidades Character da aplicação, isso não seria responsabilidade da camada de serviço/datasource? 

Abs.

**Comment by ttnunes** [comment]
Boa noite Rafael, tudo bem sim e contigo?

Sobre a função `loadCharacters` aparecer duas vezes é porque no momento que eu estava desenvolvendo a paginação, tratar os casos de avançar e voltar individualmente fazia mais sentido, mas eu concordo contigo que em uma refatoração poderia ser abstraído em um método único. Sobre essa função ainda, de ela estar implementada dentro do componente `CharactersList` eu também concordo contigo de que o componente precisar buscar e listar os dados atribui mais que uma responsabilidade neste componente e realmente seria interessante isolar a responsabilidade de buscar os dados da API em um contexto ou uma camada de serviço/datasource como tu mencionastes.

Abs.

**Comment by mstrcnvs** [comment]
Obrigado Thiago!
