### ISSUE TITLE
Storybook

### ISSUE THREAD

**Issue by mstrcnvs** [ttnunes/manga-list#2]
Boa noite Thiago, tudo bem?

Você tem experiência com o desenvolvimento e manutenção de Storybook?

Na sua opinião, qual é a importância, da aplicação possuir um Storybook atualizado?

Abs.

**Comment by ttnunes** [comment]
Boa noite Rafael, tudo bem sim e contigo?

Atualmente, uma aplicação que desenvolvo e dou manutenção utiliza Storybook. Ele tem sido usado principalmente pra documentar as propriedades dos componentes que estão sendo desenvolvidos e futuramente essa aplicação deve virar uma biblioteca base de componentes para outros projetos. O interessante dessa aplicação com o Storybook é que ele também serve como referência pra equipe de design na padronização dos elementos da interface.

Minha opinião sobre manter o Storybook atualizado é justamente de manter essa documentação de componentes, o que evita alguns problemas como o de duplicar componentes e do outro lado também acaba por agilizar o desenvolvimento e testar as diversas propriedades que o componente possua.

Abs.

**Comment by mstrcnvs** [comment]
Obrigado Thiago!
