### ISSUE TITLE
Camada de serviço

### ISSUE THREAD

**Issue by mstrcnvs** [ttnunes/manga-list#3]
https://github.com/ttnunes/manga-list/blob/f80f5b16a7c323a343e9f84deee0c975dc1ee6c2/src/services/api.ts#L1-L5

Boa noite Thiago, tudo bem?

Qual é, de acordo com a literatura, a responsabilidade da camada de serviço no contexto de uma aplicação com lógicas de negócio especificas?

Abs.

**Comment by ttnunes** [comment]
Boa noite Rafael, tudo bem sim e contigo?

De acordo com a literatura a responsabilidade da camada de serviço é de implementar as regras de negócio.

Sobre essa parte da aplicação que esta com o axios, o objetivo era de, dar ao entender com o nome `services` de que nesse ponto do sistema, esta sendo implementado um serviço que vai fornecer os dados. Normalmente tenho utilizado esse padrão de nome e de estrutura quando estou configurando uma API.

Abs.

**Comment by mstrcnvs** [comment]
Obrigado Thiago!
