### ISSUE TITLE
Classe que implementa uma Interface

### ISSUE THREAD

**Issue by mstrcnvs** [ttnunes/manga-list#4]
https://github.com/ttnunes/manga-list/blob/f80f5b16a7c323a343e9f84deee0c975dc1ee6c2/src/components/Card/index.tsx#L9-L11

Boa noite Thiago, tudo bem?

Qual, na sua opinião, seria o ganho caso esse método fosse definido em uma classe que implementa a interface Character?

Abs.

**Comment by ttnunes** [comment]
Boa noite Rafael, tudo bem sim e contigo?

O ganho seria de centralizar essa função e disponibilizar ela em cada nova instância dessa classe.

Abs.

**Comment by mstrcnvs** [comment]
Obrigado Thiago!
